// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/model', 'cmx/scene'], function(Model, Scene) {
    var SceneModel;
    return SceneModel = (function(superClass) {
      extend(SceneModel, superClass);

      function SceneModel() {
        this.defaults = {
          "width": [250, "int"],
          "height": [350, "int"],
          "frame": [true, "bool"],
          "margin-x": [10, "int"],
          "margin-y": [20, "int"]
        };
        SceneModel.__super__.constructor.apply(this, arguments);
      }

      SceneModel.prototype.applyDefaults = function(props) {
        SceneModel.__super__.applyDefaults.apply(this, arguments);
        if (props["margin"] !== void 0) {
          props["margin-x"] = props["margin"];
          props["margin-y"] = props["margin"];
        }
        return props;
      };

      SceneModel.prototype.materialize = function($where) {
        var $wrapper, id, scene;
        $wrapper = $("<div/>").attr('class', 'cmx-scene');
        id = $(this.source).attr("id");
        if (id) {
          $wrapper.addClass("cmx-user-" + id);
        }
        $where.after($wrapper);
        scene = new Scene(this.cmx, $wrapper.get(0), this.props["width"], this.props["height"], this.props["frame"], this.props["margin-x"], this.props["margin-y"]);
        SceneModel.__super__.materialize.call(this, scene);
        scene.drawScene();
        return scene;
      };

      return SceneModel;

    })(Model);
  });

}).call(this);
