// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/model', 'cmx/entities/actor'], function(Model, Actor) {
    var ActorModel;
    return ActorModel = (function(superClass) {
      extend(ActorModel, superClass);

      function ActorModel() {
        this.defaults = {
          "t": "",
          "pose": "0,0|0,106|0,90|0,80|0,70|0,50|-10,30|-10,0|10,30|10,0|-10,70|-10,50|10,70|10,50"
        };
        ActorModel.__super__.constructor.apply(this, arguments);
      }

      ActorModel.prototype.materialize = function(parent) {
        var o;
        o = new Actor(parent.scene);
        o.setFrame(this.props["t"]);
        o.setPose(this.unserializePose(this.props["pose"]));
        parent.add(o);
        return ActorModel.__super__.materialize.call(this, o);
      };

      ActorModel.prototype.read = function() {
        this.props["t"] = this.view.getFrame();
        return this.props["pose"] = this.serializePose(this.view.getPose());
      };

      return ActorModel;

    })(Model);
  });

}).call(this);
