// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/model', 'cmx/entities/bubble'], function(Model, Bubble) {
    var BubbleModel;
    return BubbleModel = (function(superClass) {
      extend(BubbleModel, superClass);

      function BubbleModel() {
        this.defaults = {
          "t": "",
          "pose": "0,0|-20,10|-40,50|0,50|-20,90|-60,85",
          "content": '<tspan x="0" y="0em">hello world</tspan>',
          "attach": "head"
        };
        BubbleModel.__super__.constructor.apply(this, arguments);
      }

      BubbleModel.prototype.materialize = function(parent) {
        var o;
        o = new Bubble(parent.scene);
        o.setFrame(this.props["t"]);
        o.setPose(this.unserializePose(this.props["pose"]));
        o.setContent(this.props.content);
        o.setAttachBone(this.props.attach);
        parent.add(o);
        return BubbleModel.__super__.materialize.call(this, o);
      };

      BubbleModel.prototype.read = function() {
        this.props["t"] = this.view.getFrame();
        return this.props["pose"] = this.serializePose(this.view.getPose());
      };

      return BubbleModel;

    })(Model);
  });

}).call(this);
