// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/model', 'cmx/entities/drawing'], function(Model, Drawing) {
    var DEFAULT_LAYER, DrawingModel;
    DEFAULT_LAYER = 2;
    return DrawingModel = (function(superClass) {
      extend(DrawingModel, superClass);

      function DrawingModel() {
        this.defaults = {
          "t": "",
          "pose": "0,0",
          "drawlist": [[], "array"]
        };
        DrawingModel.__super__.constructor.apply(this, arguments);
      }

      DrawingModel.prototype.applyDefaults = function(props) {
        var $parser, list;
        DrawingModel.__super__.applyDefaults.apply(this, arguments);
        if (props["content"]) {
          list = [];
          $parser = $("<div/>").html(props["content"]);
          $parser.children().each(function() {
            var $command, action, cmd, collectOpts, layer, points;
            $command = $(this);
            collectOpts = function($el) {
              var attr, i, key, len, ref, res, val;
              res = {};
              ref = $el.get(0).attributes;
              for (i = 0, len = ref.length; i < len; i++) {
                attr = ref[i];
                key = attr.name.toLowerCase();
                val = attr.value;
                res[key] = val;
              }
              return res;
            };
            layer = parseInt($command.attr("layer") || DEFAULT_LAYER, 10);
            action = $command.prop('tagName').toLowerCase();
            cmd = [layer, action];
            switch (action) {
              case 'line':
                points = [];
                $command.find("point").each(function() {
                  var $point, x, y;
                  $point = $(this);
                  x = parseInt($point.attr("x") || 0, 10);
                  y = parseInt($point.attr("y") || 0, 10);
                  return points.push([x, y]);
                });
                cmd.push(points);
            }
            cmd.push(collectOpts($command));
            return list.push(cmd);
          });
          props["drawlist"] = list;
        }
        return props;
      };

      DrawingModel.prototype.materialize = function(parent) {
        var o;
        o = new Drawing(parent.scene, this.props["drawlist"]);
        o.setFrame(this.props["t"]);
        o.setPose(this.unserializePose(this.props["pose"]));
        parent.add(o);
        return DrawingModel.__super__.materialize.call(this, o);
      };

      DrawingModel.prototype.read = function() {
        this.props["t"] = this.view.getFrame();
        return this.props["pose"] = this.serializePose(this.view.getPose());
      };

      return DrawingModel;

    })(Model);
  });

}).call(this);
