// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/model', 'cmx/entities/label'], function(Model, Label) {
    var LabelModel;
    return LabelModel = (function(superClass) {
      extend(LabelModel, superClass);

      function LabelModel() {
        this.defaults = {
          "t": "",
          "pose": "0,-10|0,0",
          "content": '<tspan x="0" y="0em">hello world</tspan>'
        };
        LabelModel.__super__.constructor.apply(this, arguments);
      }

      LabelModel.prototype.materialize = function(parent) {
        var o;
        o = new Label(parent.scene);
        o.setFrame(this.props["t"]);
        o.setPose(this.unserializePose(this.props["pose"]));
        o.setContent(this.props.content);
        parent.add(o);
        return LabelModel.__super__.materialize.call(this, o);
      };

      LabelModel.prototype.read = function() {
        this.props["pose"] = this.serializePose(this.view.getPose());
        return this.props["t"] = this.view.getFrame();
      };

      return LabelModel;

    })(Model);
  });

}).call(this);
