// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/entity', 'cmx/gizmos/actor_gizmo'], function(Entity, ActorGizmo) {
    var Actor;
    return Actor = (function(superClass) {
      extend(Actor, superClass);

      Actor.prototype.HEAD_RADIUS = 16;

      function Actor(scene, pose) {
        var standardHead;
        Actor.__super__.constructor.call(this, scene);
        this.actorBones = this.skelet.addBones([['HNDL', 0, 0, "h"], ['HEAD', 0, 106, "n"], ['NECK', 0, 90, "p"], ['BDC1', 0, 80, "c"], ['BDC2', 0, 70, "c"], ['HIPS', 0, 50, "p"], ['LLEG', -10, 30, "l"], ['LFOT', -10, 0, "p"], ['RLEG', 10, 30, "l"], ['RFOT', 10, 0, "p"], ['LARM', -10, 70, "l"], ['LHND', -10, 50, "p"], ['RARM', 10, 70, "l"], ['RHND', 10, 50, "p"]]);
        this.skelet.addStructure({
          'NECK': ['LARM', 'LHND', 'RARM', 'RHND', 'HEAD', 'BDC1'],
          'HIPS': ['LLEG', 'LFOT', 'RLEG', 'RFOT', 'BDC2'],
          'LARM': ['LHND'],
          'RARM': ['RHND'],
          'LLEG': ['LFOT'],
          'RLEG': ['RFOT'],
          'HNDL': ['HEAD', 'NECK', 'BDC1', 'BDC2', 'HIPS', 'LLEG', 'LFOT', 'RLEG', 'RFOT', 'LARM', 'LHND', 'RARM', 'RHND']
        });
        this.legs = [['HIPS', 'LLEG', 'LFOT'], ['HIPS', 'RLEG', 'RFOT']];
        this.arms = [['NECK', 'LARM', 'LHND'], ['NECK', 'RARM', 'RHND']];
        standardHead = (function(_this) {
          return function() {
            return _this.scene.renderer.circle(_this.HEAD_RADIUS, {
              t: "translate(0, " + _this.HEAD_RADIUS + ")"
            });
          };
        })(this);
        this.heads = {
          "normal": function() {
            return standardHead();
          },
          "line": function() {
            standardHead();
            return this.scene.renderer.line([[0, 20], [0, 40]]);
          }
        };
        this.head = "normal";
        if (pose) {
          this.setPose(pose);
        }
      }

      Actor.prototype.buildGizmo = function(root) {
        return this.gizmo = new ActorGizmo(this, root);
      };

      Actor.prototype.setPose = function(pose) {
        return this.skelet.setPose(pose, this.actorBones);
      };

      Actor.prototype.getPose = function() {
        return this.skelet.getPose(this.actorBones);
      };

      Actor.prototype.drawBody = function() {
        var bodyPath, bone;
        bone = (function(_this) {
          return function(name) {
            return _this.skelet.bone(name);
          };
        })(this);
        bodyPath = (function(_this) {
          return function() {
            var f;
            f = function(n) {
              return " " + (bone(n).x) + "," + (bone(n).y);
            };
            return "M" + (f('NECK')) + " C" + (f('BDC1')) + (f('BDC2')) + (f('HIPS'));
          };
        })(this);
        return this.register(this.scene.renderer.path(((function(_this) {
          return function() {
            return bodyPath();
          };
        })(this))));
      };

      Actor.prototype.drawHead = function() {
        var bone;
        bone = (function(_this) {
          return function(name) {
            return _this.skelet.bone(name);
          };
        })(this);
        this.openFrame(((function(_this) {
          return function() {
            return _this.prepareFrame(bone('NECK'), bone('HEAD'));
          };
        })(this)));
        this.heads[this.head].apply(this);
        return this.closeFrame();
      };

      Actor.prototype.drawLegs = function() {
        var bonePos;
        bonePos = (function(_this) {
          return function(name) {
            var bone;
            bone = _this.skelet.bone(name);
            return [bone.x, bone.y];
          };
        })(this);
        this.register(this.scene.renderer.line(((function(_this) {
          return function() {
            return _this.legs[0].map(bonePos);
          };
        })(this))));
        return this.register(this.scene.renderer.line(((function(_this) {
          return function() {
            return _this.legs[1].map(bonePos);
          };
        })(this))));
      };

      Actor.prototype.drawArms = function() {
        var bonePos;
        bonePos = (function(_this) {
          return function(name) {
            var bone;
            bone = _this.skelet.bone(name);
            return [bone.x, bone.y];
          };
        })(this);
        this.register(this.scene.renderer.line(((function(_this) {
          return function() {
            return _this.arms[0].map(bonePos);
          };
        })(this))));
        return this.register(this.scene.renderer.line(((function(_this) {
          return function() {
            return _this.arms[1].map(bonePos);
          };
        })(this))));
      };

      Actor.prototype.drawLayer = function(layer) {
        Actor.__super__.drawLayer.apply(this, arguments);
        if (layer === 2) {
          this.drawHead();
        }
        if (layer === 2) {
          this.drawBody();
        }
        if (layer === 2) {
          this.drawArms();
        }
        if (layer === 2) {
          return this.drawLegs();
        }
      };

      return Actor;

    })(Entity);
  });

}).call(this);
