// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/entity', 'cmx/gizmos/bubble_gizmo'], function(Entity, BubbleGizmo) {
    var Bubble;
    return Bubble = (function(superClass) {
      extend(Bubble, superClass);

      function Bubble(scene, content) {
        Bubble.__super__.constructor.call(this, scene);
        this.bubbleBones = this.skelet.addBones([['HNDL', 0, 0, "h"], ['LINE', -20, 10, "p"], ['LCP1', -40, 50, "c"], ['LCP2', 0, 50, "c"], ['LEND', -20, 90, "p"], ['TEXT', -80, 130, "t"]]);
        this.skelet.addStructure({
          'HNDL': ['LINE', 'LCP1', 'LCP2', 'LEND', 'TEXT'],
          'LEND': ['LCP2'],
          'LINE': ['LCP1']
        });
        this.setContent(content);
      }

      Bubble.prototype.buildGizmo = function(root) {
        return this.gizmo = new BubbleGizmo(this, root);
      };

      Bubble.prototype.setPose = function(pose) {
        return this.skelet.setPose(pose, this.bubbleBones);
      };

      Bubble.prototype.getPose = function() {
        return this.skelet.getPose(this.bubbleBones);
      };

      Bubble.prototype.setContent = function(content1) {
        this.content = content1;
      };

      Bubble.prototype.drawLine = function() {
        var bodyPath, bone;
        bone = (function(_this) {
          return function(name) {
            return _this.skelet.bone(name);
          };
        })(this);
        bodyPath = (function(_this) {
          return function() {
            var f;
            f = function(n) {
              return " " + (bone(n).x) + "," + (bone(n).y);
            };
            return "M" + (f('LINE')) + " C" + (f('LCP1')) + (f('LCP2')) + (f('LEND'));
          };
        })(this);
        return this.register(this.scene.renderer.path(((function(_this) {
          return function() {
            return bodyPath();
          };
        })(this)), {
          "stroke-width": 2
        }));
      };

      Bubble.prototype.drawText = function() {
        var f;
        f = (function(_this) {
          return function(bone) {
            return " " + bone.x + "," + bone.y;
          };
        })(this);
        this.register(this.scene.renderer.openGroup({
          t: ((function(_this) {
            return function() {
              return "translate (" + (f(_this.skelet.bone('TEXT'))) + ")";
            };
          })(this))
        }));
        this.register(this.scene.renderer.text(this.content));
        return this.register(this.scene.renderer.closeGroup());
      };

      Bubble.prototype.drawLayer = function(layer) {
        Bubble.__super__.drawLayer.apply(this, arguments);
        if (layer === 2) {
          this.drawLine();
        }
        if (layer === 1) {
          return this.drawText();
        }
      };

      return Bubble;

    })(Entity);
  });

}).call(this);
