// Generated by CoffeeScript 1.12.7
(function() {
  var slice = [].slice;

  define(['cmx/controller', 'cmx/model', 'cmx/view', 'cmx/drawable', 'cmx/xkcd', 'cmx/bone', 'cmx/skelet', 'cmx/scene', 'cmx/entity', 'cmx/gizmo', 'cmx/renderer', 'cmx/overlay', 'cmx/parser', 'cmx/entities/actor', 'cmx/entities/bubble', 'cmx/entities/drawing', 'cmx/entities/label', 'cmx/gizmos/entity_gizmo', 'cmx/gizmos/actor_gizmo', 'cmx/gizmos/bubble_gizmo', 'cmx/gizmos/drawing_gizmo', 'cmx/gizmos/label_gizmo', 'cmx/models/scene_model', 'cmx/models/actor_model', 'cmx/models/bubble_model', 'cmx/models/drawing_model', 'cmx/models/label_model'], function() {
    var classes, cmx, i, klass, len;
    classes = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    cmx = new classes[0];
    for (i = 0, len = classes.length; i < len; i++) {
      klass = classes[i];
      cmx[klass.name] = klass;
    }
    return cmx;
  });

}).call(this);
