// Generated by CoffeeScript 1.12.7
(function() {
  require.config({
    paths: {
      'jquery': 'vendor/jquery',
      'd3': 'vendor/d3/d3',
      'svginnerhtml': 'vendor/svginnerhtml',
      'underscore': 'vendor/underscore-amd/underscore',
      'underscore.string': 'vendor/underscore.string/lib/underscore.string',
      'cmx': '../../lib/cmx',
      'd3ext': 'd3ext'
    }
  });

  require(['jquery', 'd3', 'd3ext', 'underscore', 'underscore.string', 'svginnerhtml', 'cmx'], function(_jq, _d3, d3ext, underscore, underscoreString, _svginnerhtml, cmx) {
    var launch, loadWebFonts, publishEvent;
    publishEvent = function(name) {
      console.log("" + name);
      $("body").trigger(name, cmx);
      return typeof parent !== "undefined" && parent !== null ? typeof parent.messageFromCMX === "function" ? parent.messageFromCMX(name, cmx) : void 0 : void 0;
    };
    loadWebFonts = function(continuation) {
      var alreadyCalled, checkIfLoaderIsBroken, s, wf;
      alreadyCalled = false;
      window.WebFontConfig = {
        custom: {
          families: ["xkcd"]
        },
        active: function() {
          alreadyCalled = true;
          return typeof continuation === "function" ? continuation() : void 0;
        }
      };
      wf = document.createElement("script");
      wf.src = "//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js";
      wf.type = "text/javascript";
      wf.async = "true";
      s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(wf, s);
      checkIfLoaderIsBroken = function() {
        if (!alreadyCalled) {
          return typeof continuation === "function" ? continuation() : void 0;
        }
      };
      return setTimeout(checkIfLoaderIsBroken, 2000);
    };
    launch = function() {
      var $scene, i, len, parser, sceneModel, sceneModels;
      cmx.previousCmx = window.cmx;
      window.cmx = cmx;
      publishEvent("cmx:launched");
      parser = new cmx.Parser(cmx);
      sceneModels = parser.parseDoc($("body"));
      for (i = 0, len = sceneModels.length; i < len; i++) {
        sceneModel = sceneModels[i];
        $scene = $(sceneModel.source);
        console.log("model for #" + ($scene.attr("id")) + ":", this);
        sceneModel.debugReport(2);
        sceneModel.materialize($scene);
      }
      return publishEvent("cmx:ready");
    };
    publishEvent("cmx:loaded");
    underscore.string = underscore.str = underscoreString;
    d3ext();
    return loadWebFonts(launch);
  });

}).call(this);
