// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/gizmos/entity_gizmo'], function(EntityGizmo) {
    var ActorGizmo;
    return ActorGizmo = (function(superClass) {
      extend(ActorGizmo, superClass);

      function ActorGizmo() {
        return ActorGizmo.__super__.constructor.apply(this, arguments);
      }

      ActorGizmo.prototype.update = function() {
        var ref;
        ActorGizmo.__super__.update.apply(this, arguments);
        return (ref = this.ΔskeletonGizmo) != null ? ref.selectAll(".cmx-control").attr("cx", function(bone) {
          return bone.x;
        }).attr("cy", function(bone) {
          return bone.y;
        }).style("display", (function(_this) {
          return function(bone) {};
        })(this)) : void 0;
      };

      ActorGizmo.prototype.build = function() {
        var alignBone, base, data, doubleClick, drag, resetBone;
        base = ActorGizmo.__super__.build.apply(this, arguments);
        this.ΔskeletonGizmo = base.append("g").attr("class", "cmx-gizmo cmx-actor");
        alignBone = (function(_this) {
          return function(bone) {
            var a, b, ud;
            if (bone.name === 'LLEG') {
              ud = _this.entity.legs[0];
            }
            if (bone.name === 'RLEG') {
              ud = _this.entity.legs[1];
            }
            if (bone.name === 'LARM') {
              ud = _this.entity.arms[0];
            }
            if (bone.name === 'RARM') {
              ud = _this.entity.arms[1];
            }
            a = _this.entity.skelet.bone(ud[0]);
            b = _this.entity.skelet.bone(ud[2]);
            bone.x = Math.round((a.x + b.x) / 2);
            bone.y = Math.round((a.y + b.y) / 2);
            return _this.entity.update();
          };
        })(this);
        resetBone = (function(_this) {
          return function(bone) {
            _this.entity.skelet.moveBone(bone.name, 0, 0, true);
            return _this.entity.throttledUpdate();
          };
        })(this);
        doubleClick = (function(_this) {
          return function(bone) {
            d3.event.preventDefault();
            if (bone.type === "l") {
              return alignBone(bone);
            }
            if (bone.name === 'HNDL') {
              return resetBone(bone);
            }
          };
        })(this);
        drag = d3.behavior.drag().on("dragstart", (function(_this) {
          return function(bone) {
            _this.controlUndoOpen("pose");
            return _this.controlDragStart(bone);
          };
        })(this)).on("dragend", (function(_this) {
          return function(bone) {
            _this.controlDragEnd(bone);
            return _this.controlUndoClose();
          };
        })(this)).on("drag", (function(_this) {
          return function(bone) {
            _this.entity.skelet.moveBone(bone.name, d3.event.dx, d3.event.dy, false);
            return _this.entity.throttledUpdate();
          };
        })(this));
        data = this.entity.skelet.bonesWithIndices(this.entity.actorBones);
        this.ΔskeletonGizmo.selectAll(".cmx-control").data(data).enter().append("circle").attr("class", function(bone) {
          return "cmx-control cmx-" + bone.type;
        }).attr("r", this.CONTROL_POINT_RADIUS).on("dblclick", doubleClick).call(drag);
        return this.ΔskeletonGizmo;
      };

      return ActorGizmo;

    })(EntityGizmo);
  });

}).call(this);
