// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/gizmo'], function(Gizmo) {
    var EntityGizmo, MARKER_POS, MARKER_ROT, MARKER_SQ, MARKER_SX, MARKER_SY;
    MARKER_POS = 0;
    MARKER_ROT = 1;
    MARKER_SX = 2;
    MARKER_SY = 3;
    MARKER_SQ = 4;
    return EntityGizmo = (function(superClass) {
      extend(EntityGizmo, superClass);

      function EntityGizmo() {
        this.entityMarkers = [
          {
            kind: "pos",
            val: [0, 0]
          }, {
            kind: "rot",
            val: 0
          }, {
            kind: "sx",
            val: 1
          }, {
            kind: "sy",
            val: 1
          }, {
            kind: "sq",
            val: 0
          }
        ];
        EntityGizmo.__super__.constructor.apply(this, arguments);
      }

      EntityGizmo.prototype.markerPosition = function(marker) {
        switch (marker.kind) {
          case "pos":
            return {
              x: 0,
              y: 0
            };
          case "rot":
            return {
              x: 15,
              y: 15
            };
          case "sx":
            return {
              x: 10,
              y: 0
            };
          case "sy":
            return {
              x: 0,
              y: 10
            };
          case "sq":
            return {
              x: marker.val,
              y: -10
            };
          default:
            throw "unknown marker";
        }
      };

      EntityGizmo.prototype.decomposeFrame = function(frame) {
        var t;
        t = d3.transform(frame);
        this.entityMarkers[MARKER_POS].val[0] = t.translate[0];
        this.entityMarkers[MARKER_POS].val[1] = t.translate[1];
        this.entityMarkers[MARKER_ROT].val = t.rotate;
        this.entityMarkers[MARKER_SX].val = t.scale[0];
        this.entityMarkers[MARKER_SY].val = t.scale[1];
        return this.entityMarkers[MARKER_SQ].val = t.skew;
      };

      EntityGizmo.prototype.composeFrame = function() {
        var round, t;
        round = function(v, p) {
          if (p == null) {
            p = 1;
          }
          return Math.round(v * p) / p;
        };
        t = d3.transform();
        t.translate[0] = round(this.entityMarkers[MARKER_POS].val[0]);
        t.translate[1] = round(this.entityMarkers[MARKER_POS].val[1]);
        t.rotate = round(this.entityMarkers[MARKER_ROT].val);
        t.scale[0] = round(this.entityMarkers[MARKER_SX].val, 100);
        t.scale[1] = round(this.entityMarkers[MARKER_SY].val, 100);
        t.skew = round(this.entityMarkers[MARKER_SQ].val);
        return t.toString();
      };

      EntityGizmo.prototype.update = function() {
        var ref;
        if ((ref = this.ΔentityGizmo) != null) {
          ref.attr("transform", this.entity.getEffectiveFrame()).selectAll(".cmx-marker").attr("transform", (function(_this) {
            return function(marker) {
              var pos;
              pos = _this.markerPosition(marker);
              return "translate(" + pos.x + "," + pos.y + ")";
            };
          })(this));
        }
        return this;
      };

      EntityGizmo.prototype.build = function(root) {
        var base, doubleClick, drag, renderMarker, selection;
        base = EntityGizmo.__super__.build.apply(this, arguments);
        this.ΔentityGizmo = base.append("g").attr("class", "cmx-gizmo cmx-entity");
        doubleClick = (function(_this) {
          return function(marker) {
            d3.event.preventDefault();
            switch (marker.kind) {
              case "pos":
                marker.val = [0, 0];
                break;
              case "rot":
                marker.val = 0;
                break;
              case "sx":
                marker.val = 1;
                break;
              case "sy":
                marker.val = 1;
                break;
              case "sq":
                marker.val = 0;
            }
            _this.entity.setFrame(_this.composeFrame());
            return _this.entity.throttledUpdate();
          };
        })(this);
        drag = d3.behavior.drag().base((function(_this) {
          return function(target) {
            return target.parentNode.parentNode;
          };
        })(this)).on("dragstart", (function(_this) {
          return function(bone) {
            _this.controlUndoOpen("frame");
            return _this.controlDragStart(bone);
          };
        })(this)).on("dragend", (function(_this) {
          return function(bone) {
            _this.controlDragEnd(bone);
            return _this.controlUndoClose();
          };
        })(this)).on("drag", (function(_this) {
          return function(marker) {
            _this.decomposeFrame(_this.entity.getFrame());
            switch (marker.kind) {
              case "pos":
                marker.val[0] += d3.event.dx;
                marker.val[1] += d3.event.dy;
                break;
              case "rot":
                marker.val += d3.event.dx + d3.event.dy;
                break;
              case "sx":
                marker.val += d3.event.dx * 0.1;
                break;
              case "sy":
                marker.val += d3.event.dy * 0.1;
                break;
              case "sq":
                marker.val += d3.event.dx;
            }
            _this.entity.setFrame(_this.composeFrame());
            return _this.entity.throttledUpdate();
          };
        })(this));
        renderMarker = function(marker) {
          var appendLine, appendRect, Δ;
          Δ = d3.select(this);
          appendRect = function(Δ, x, y, w, h) {
            return Δ.append("rect").attr("x", x).attr("y", y).attr("width", w).attr("height", h);
          };
          appendLine = function(Δ, x1, y1, x2, y2) {
            return Δ.append("line").attr("x1", x1).attr("y1", y1).attr("x2", x2).attr("y2", y2);
          };
          if (marker.kind !== "rot") {
            appendRect(Δ, -5, -5, 10, 10);
          }
          switch (marker.kind) {
            case "pos":
              appendLine(Δ, -5, 0, 5, 0);
              return appendLine(Δ, 0, -5, 0, 5);
            case "rot":
              appendRect(Δ, -10, -10, 15, 15);
              return Δ.append("path").attr("transform", "translate(-8, -8)").attr("d", "M0,10 A10 10,0,0,0,10 0");
            case "sx":
              return appendLine(Δ, -5, 0, 5, 0);
            case "sy":
              return appendLine(Δ, 0, -5, 0, 5);
            case "sq":
              return appendLine(Δ, -5, 0, 5, 0);
          }
        };
        selection = this.ΔentityGizmo.selectAll(".cmx-marker").data(this.entityMarkers).enter().append("g").attr("class", function(marker) {
          return "cmx-control cmx-marker cmx-" + marker.kind;
        }).on("dblclick", doubleClick).call(drag);
        selection.each(renderMarker);
        return this.ΔentityGizmo;
      };

      return EntityGizmo;

    })(Gizmo);
  });

}).call(this);
