// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/gizmos/entity_gizmo'], function(EntityGizmo) {
    var LabelGizmo;
    return LabelGizmo = (function(superClass) {
      extend(LabelGizmo, superClass);

      function LabelGizmo() {
        return LabelGizmo.__super__.constructor.apply(this, arguments);
      }

      LabelGizmo.prototype.update = function() {
        var ref;
        LabelGizmo.__super__.update.apply(this, arguments);
        return (ref = this.ΔskeletonGizmo) != null ? ref.selectAll(".cmx-control").attr("cx", function(bone) {
          return bone.x;
        }).attr("cy", function(bone) {
          return bone.y;
        }).style("display", (function(_this) {
          return function(bone) {};
        })(this)) : void 0;
      };

      LabelGizmo.prototype.build = function() {
        var base, data, doubleClick, drag, resetBone;
        base = LabelGizmo.__super__.build.apply(this, arguments);
        this.ΔskeletonGizmo = base.append("g").attr("class", "cmx-gizmo cmx-label");
        resetBone = (function(_this) {
          return function(bone) {
            _this.entity.skelet.moveBone(bone.name, 0, 0, true);
            return _this.entity.throttledUpdate();
          };
        })(this);
        doubleClick = (function(_this) {
          return function(bone) {
            d3.event.preventDefault();
            if (bone.name === 'HNDL') {
              return resetBone(bone);
            }
            if (bone.name === 'TEXT') {
              return resetBone(bone);
            }
          };
        })(this);
        drag = d3.behavior.drag().on("dragstart", (function(_this) {
          return function(bone) {
            _this.controlUndoOpen("pose");
            return _this.controlDragStart(bone);
          };
        })(this)).on("dragend", (function(_this) {
          return function(bone) {
            _this.controlDragEnd(bone);
            return _this.controlUndoClose();
          };
        })(this)).on("drag", (function(_this) {
          return function(bone) {
            _this.entity.skelet.moveBone(bone.name, d3.event.dx, d3.event.dy, false);
            return _this.entity.throttledUpdate();
          };
        })(this));
        data = this.entity.skelet.bonesWithIndices(this.entity.labelBones);
        this.ΔskeletonGizmo.selectAll(".cmx-control").data(data).enter().append("circle").attr("class", function(bone) {
          return "cmx-control cmx-" + bone.type;
        }).attr("r", this.CONTROL_POINT_RADIUS).on("dblclick", doubleClick).call(drag);
        return this.ΔskeletonGizmo;
      };

      return LabelGizmo;

    })(EntityGizmo);
  });

}).call(this);
