// Generated by CoffeeScript 1.12.7
(function() {
  define(function() {
    var Bone;
    return Bone = (function() {
      function Bone(name, x, y, type) {
        this.name = name;
        this.x = x;
        this.y = y;
        this.type = type != null ? type : "";
      }

      return Bone;

    })();
  });

}).call(this);
