// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/view'], function(View) {
    var Drawable;
    return Drawable = (function(superClass) {
      extend(Drawable, superClass);

      function Drawable(scene) {
        this.renderCalls = [];
        Drawable.__super__.constructor.call(this, scene);
      }

      Drawable.prototype.register = function(renderCall) {
        this.renderCalls.push(renderCall);
        return renderCall;
      };

      Drawable.prototype.draw = function(layer) {
        var i, len1, ref, view;
        if (typeof this.openLayer === "function") {
          this.openLayer(layer);
        }
        if (typeof this.drawLayer === "function") {
          this.drawLayer(layer);
        }
        ref = this.subviews;
        for (i = 0, len1 = ref.length; i < len1; i++) {
          view = ref[i];
          view.draw(layer);
        }
        return typeof this.closeLayer === "function" ? this.closeLayer(layer) : void 0;
      };

      Drawable.prototype.prepareFrame = function(framePos, frameRot) {
        var angle, f, frame, len, r, ref, vecAngle, vx, vy;
        r = function(num) {
          return Math.round(num);
        };
        f = function(p) {
          return (r(p.x)) + "," + (r(p.y));
        };
        frame = [];
        if (framePos) {
          frame.push("translate(" + (f(framePos)) + ")");
        }
        if (frameRot && framePos) {
          vecAngle = function(x, y) {
            var angle, dot, len, rad;
            len = Math.sqrt(x * x + y * y);
            dot = x / len;
            rad = Math.acos(dot);
            angle = rad * (360 / (2 * Math.PI)) - 90;
            if (y < 0) {
              angle = 180 - angle;
            }
            return [angle, len];
          };
          vx = frameRot.x - framePos.x;
          vy = frameRot.y - framePos.y;
          ref = vecAngle(vx, vy), angle = ref[0], len = ref[1];
          frame.push("rotate(" + (r(angle)) + ")");
        }
        return frame.join("");
      };

      Drawable.prototype.openFrame = function(frame, opts) {
        if (opts == null) {
          opts = {};
        }
        opts["t"] = frame;
        return this.register(this.scene.renderer.openGroup(opts));
      };

      Drawable.prototype.closeFrame = function() {
        return this.scene.renderer.closeGroup();
      };

      Drawable.prototype.buildGizmo = function(root) {
        return {
          leafGizmo: root
        };
      };

      Drawable.prototype.buildGizmos = function(root) {
        var i, len1, newRoot, ref, results, view;
        newRoot = typeof this.buildGizmo === "function" ? this.buildGizmo(root) : void 0;
        ref = this.subviews;
        results = [];
        for (i = 0, len1 = ref.length; i < len1; i++) {
          view = ref[i];
          if (typeof view.buildGizmos === "function") {
            view.buildGizmos(newRoot.leafGizmo);
          }
          results.push(view.gizmo.update());
        }
        return results;
      };

      Drawable.prototype.update = function() {
        var call, i, len1, ref, ref1;
        if ((ref = this.gizmo) != null) {
          ref.update();
        }
        ref1 = this.renderCalls;
        for (i = 0, len1 = ref1.length; i < len1; i++) {
          call = ref1[i];
          call.update();
        }
        this.updateDependants();
        this.scene.announceUpdate();
        return this;
      };

      Drawable.prototype.updateDependants = function() {
        var i, len1, ref, view;
        ref = this.subviews;
        for (i = 0, len1 = ref.length; i < len1; i++) {
          view = ref[i];
          view.update();
        }
        return this;
      };

      Drawable.prototype.throttledUpdate = _.throttle(Drawable.prototype.update, 50);

      return Drawable;

    })(View);
  });

}).call(this);
