// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['cmx/drawable', 'cmx/gizmos/entity_gizmo', 'cmx/skelet'], function(Drawable, EntityGizmo, Skelet) {
    var Entity;
    return Entity = (function(superClass) {
      extend(Entity, superClass);

      function Entity(scene) {
        Entity.__super__.constructor.call(this, scene);
        this.skelet = new Skelet;
      }

      Entity.prototype.setFrame = function(t) {
        this.t = t;
      };

      Entity.prototype.getFrame = function() {
        var re;
        re = /\)([^ ])/;
        return _.str.trim(this.t.replace("translate(0,0)", "").replace("rotate(0)", "").replace("skewX(0)", "").replace("scale(1,1)", "").replace(re, ") $1"));
      };

      Entity.prototype.getEffectiveFrame = function() {
        var boneFrame, frame;
        frame = [];
        boneFrame = this.getAttachBoneFrame();
        if (boneFrame) {
          frame.push(boneFrame);
        }
        frame.push(this.t);
        return frame.join("");
      };

      Entity.prototype.getAttachBoneFrame = function() {
        var attachBone;
        if (this.attachBone && this.parentView.skelet) {
          attachBone = this.parentView.skelet.bone(this.attachBone);
        }
        return this.prepareFrame(attachBone);
      };

      Entity.prototype.openLayer = function(layer) {
        return this.openFrame(((function(_this) {
          return function() {
            return _this.getEffectiveFrame();
          };
        })(this)), {
          "class": "cmx-entity cmx-" + (this.constructor.name.toLowerCase()),
          "data": {
            "entity": this
          }
        });
      };

      Entity.prototype.drawLayer = function(layer) {};

      Entity.prototype.closeLayer = function(layer) {
        return this.closeFrame();
      };

      Entity.prototype.setAttachBone = function(boneName) {
        return this.attachBone = boneName.toUpperCase();
      };

      Entity.prototype.buildGizmo = function(root) {
        return this.gizmo = new EntityGizmo(this, root);
      };

      Entity.prototype.highlightBones = function(root, bones) {
        if (bones == null) {
          bones = [];
        }
        if (!root) {
          return;
        }
        return root.selectAll(".cmx-control").each(function(d, bone) {
          var ref;
          if (ref = d.name, indexOf.call(bones, ref) >= 0) {
            return d3.select(this).classed("cmx-highlighted-bone", true);
          }
        });
      };

      Entity.prototype.unhighlightBones = function(root) {
        if (!root) {
          return;
        }
        return root.selectAll(".cmx-highlighted-bone").each(function(d, bone) {
          return d3.select(this).classed("cmx-highlighted-bone", false);
        });
      };

      return Entity;

    })(Drawable);
  });

}).call(this);
