// Generated by CoffeeScript 1.12.7
(function() {
  define(function() {
    var Model;
    return Model = (function() {
      function Model(cmx) {
        this.cmx = cmx;
        this.children = [];
        this.props = typeof this.applyDefaults === "function" ? this.applyDefaults({}) : void 0;
        this.mutableProps = ["t", "pose"];
      }

      Model.prototype.set = function(props) {
        props = typeof this.applyDefaults === "function" ? this.applyDefaults(props) : void 0;
        props = _.pick(props, _.keys(this.defaults));
        props = typeof this.coerceTypes === "function" ? this.coerceTypes(props) : void 0;
        return _.extend(this.props, props);
      };

      Model.prototype.unserializePose = function(poseString) {
        var items;
        items = poseString.split("|");
        return items.map(function(pair) {
          return pair.split(",").map(function(numString) {
            return parseFloat(numString);
          });
        });
      };

      Model.prototype.serializePose = function(pose) {
        var pairs;
        pairs = pose.map(function(pair) {
          return pair.join(",");
        });
        return pairs.join("|");
      };

      Model.prototype.computeDefaults = function() {
        var defaults, key, ref, val;
        defaults = {};
        ref = this.defaults;
        for (key in ref) {
          val = ref[key];
          if (_.isArray(val)) {
            val = val[0];
          }
          defaults[key] = val;
        }
        return defaults;
      };

      Model.prototype.applyDefaults = function(props) {
        var defaults;
        defaults = this.computeDefaults();
        _.defaults(props, defaults);
        return props;
      };

      Model.prototype.coerceTypes = function(props) {
        var def, key, res, type, val;
        res = {};
        for (key in props) {
          val = props[key];
          def = this.defaults[key];
          if (def === void 0) {
            continue;
          }
          type = def[1] || "string";
          res[key] = (function() {
            switch (type) {
              case "s":
              case "string":
                return "" + val;
              case "i":
              case "int":
                return parseInt(val, 10) || 0;
              case "f":
              case "float":
                return parseFloat(val) || 0.0;
              case "a":
              case "array":
                return val;
              case "b":
              case "bool":
                if (_.isString(val)) {
                  return val.match(/^(true|1|yes)$/i) !== null;
                } else {
                  return !!val;
                }
                break;
              default:
                return val;
            }
          })();
        }
        return res;
      };

      Model.prototype.read = function() {};

      Model.prototype.writeProps = function(props, $source) {
        var defaults, prop, ref, results, val;
        defaults = this.computeDefaults();
        ref = _.pick(props, this.mutableProps);
        results = [];
        for (prop in ref) {
          val = ref[prop];
          if (val === defaults[prop]) {
            results.push($source.removeAttr(prop));
          } else {
            results.push($source.attr(prop, val));
          }
        }
        return results;
      };

      Model.prototype.serialize = function() {
        var child, i, len, ref;
        this.read();
        this.writeProps(this.props, $(this.source));
        ref = this.children;
        for (i = 0, len = ref.length; i < len; i++) {
          child = ref[i];
          child.serialize();
        }
        return this;
      };

      Model.prototype.materialize = function(newborn) {
        var child, i, len, ref;
        ref = this.children;
        for (i = 0, len = ref.length; i < len; i++) {
          child = ref[i];
          child.materialize(newborn);
        }
        return this.view = newborn;
      };

      Model.prototype.debugReport = function(indent, logger) {
        var child, displayableProps, i, indenting, j, len, ref, results, results1;
        if (indent == null) {
          indent = 0;
        }
        if (logger == null) {
          logger = console;
        }
        indenting = (function() {
          results = [];
          for (var i = 0; 0 <= indent ? i < indent : i > indent; 0 <= indent ? i++ : i--){ results.push(i); }
          return results;
        }).apply(this).map(function() {
          return " ";
        }).join("");
        displayableProps = _.clone(this.props);
        if (_.isString(displayableProps["content"]) && displayableProps["content"].indexOf("\n") !== -1) {
          displayableProps["content"] = "...";
        }
        logger.log("" + indenting + this.constructor.name, displayableProps);
        ref = this.children;
        results1 = [];
        for (j = 0, len = ref.length; j < len; j++) {
          child = ref[j];
          results1.push(child.debugReport(indent + 2, logger));
        }
        return results1;
      };

      return Model;

    })();
  });

}).call(this);
