// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/drawable', 'cmx/renderer', 'cmx/overlay', 'cmx/gizmo'], function(Drawable, Renderer, Overlay, Gizmo) {
    var Scene;
    return Scene = (function(superClass) {
      extend(Scene, superClass);

      function Scene(cmx, rootElement, width, height, frame1, marginX, marginY) {
        this.cmx = cmx;
        this.rootElement = rootElement;
        this.width = width != null ? width : 300;
        this.height = height != null ? height : 400;
        this.frame = frame1 != null ? frame1 : true;
        this.marginX = marginX != null ? marginX : 20;
        this.marginY = marginY != null ? marginY : 20;
        Scene.__super__.constructor.call(this, this);
        this.renderer = new Renderer(this.rootElement, this.width, this.height, this.marginX, this.marginY);
        this;
      }

      Scene.prototype.drawScene = function() {
        var i, layerId, layers, ref, results, view, Δentity, Δg, Δlayer;
        this.renderer.Δlayers.selectAll("g").remove();
        layers = [d3.select(document.createElementNS(d3.ns.prefix.svg, "g")).attr("class", "cmx-layer cmx-layer-0"), d3.select(document.createElementNS(d3.ns.prefix.svg, "g")).attr("class", "cmx-layer cmx-layer-1"), d3.select(document.createElementNS(d3.ns.prefix.svg, "g")).attr("class", "cmx-layer cmx-layer-2")];
        results = [];
        for (layerId = i = ref = layers.length - 1; ref <= 0 ? i <= 0 : i >= 0; layerId = ref <= 0 ? ++i : --i) {
          if (layerId === 0 && this.frame) {
            Δg = d3.select(document.createElementNS(d3.ns.prefix.svg, "g"));
            Δg.attr("class", "cmx-layer cmx-layer-frame");
            Δlayer = Δg.append("g");
            Δlayer.attr("class", "cmx-pseudo-entity cmx-frame");
            this.renderer.Δlayers.node().appendChild(Δlayer.node().parentNode);
            this.drawFrame(Δlayer);
          }
          Δlayer = layers[layerId];
          this.renderer.Δlayers.node().appendChild(Δlayer.node());
          results.push((function() {
            var j, len, ref1, results1;
            ref1 = this.subviews;
            results1 = [];
            for (j = 0, len = ref1.length; j < len; j++) {
              view = ref1[j];
              Δentity = d3.select(document.createElementNS(d3.ns.prefix.svg, "g")).attr("class", "cmx-entity-tree");
              Δlayer.node().appendChild(Δentity.node());
              view.draw(layerId);
              results1.push(this.renderer.draw(Δentity));
            }
            return results1;
          }).call(this));
        }
        return results;
      };

      Scene.prototype.triggerUpdateEvent = function() {
        return $(this.rootElement).trigger("cmx:updated");
      };

      Scene.prototype.announceUpdate = _.throttle(Scene.prototype.triggerUpdateEvent, 2000);

      Scene.prototype.buildGizmos = function() {
        this.overlay = new Overlay(this.rootElement, this.width, this.height, this.marginX, this.marginY);
        Scene.__super__.buildGizmos.call(this, this.overlay.Δgizmos);
        return this.renderer.Δlayers.selectAll(".cmx-entity").on("click", function(event) {
          var gizmo, ref, ref1;
          gizmo = (ref = this.cmx) != null ? (ref1 = ref.entity) != null ? ref1.gizmo : void 0 : void 0;
          if (gizmo) {
            gizmo.select();
            return d3.event.stopPropagation();
          }
        });
      };

      Scene.prototype.drawFrame = function(Δwhere) {
        var frame, thickness;
        thickness = 0;
        frame = [[thickness, thickness], [this.width - thickness, thickness], [this.width - thickness, this.height - thickness], [thickness, this.height - thickness], [thickness, thickness]];
        this.renderer.line(frame);
        return this.renderer.draw(Δwhere);
      };

      return Scene;

    })(Drawable);
  });

}).call(this);
