// Generated by CoffeeScript 1.12.7
(function() {
  define(function() {
    var View;
    return View = (function() {
      function View(scene) {
        this.scene = scene;
        this.subviews = [];
      }

      View.prototype.add = function(view) {
        view.parentView = this;
        this.subviews.push(view);
        return view;
      };

      return View;

    })();
  });

}).call(this);
