// Generated by CoffeeScript 1.12.7
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(function() {
    return function() {
      return d3.selection.prototype.parents = function(selector) {
        var e, items, klass, p, res;
        res = [];
        p = this.node();
        while (p = p.parentNode) {
          try {
            klass = d3.select(p).attr("class");
          } catch (error) {
            e = error;
          }
          if (!klass) {
            continue;
          }
          items = klass.split(" ");
          if (indexOf.call(items, selector) >= 0) {
            res.push(p);
          }
        }
        return res;
      };
    };
  });

}).call(this);
