// Generated by CoffeeScript 1.12.7
(function() {
  var displayHomepage, loadAndDisplayGist;

  displayHomepage = function() {
    $('html').addClass('force-vscrollbar');
    $("#homepage").css("display", "block");
    return _gaq.push(['_trackPageview']);
  };

  loadAndDisplayGist = function(gistId) {
    var fail, spinner, spinnerOpts, src;
    $("#comix-spinner").show();
    document.title = "Comix #" + gistId;
    spinnerOpts = {
      lines: 10,
      length: 5,
      width: 3,
      radius: 4,
      corners: 1,
      rotate: 15,
      color: '#666',
      speed: 1,
      trail: 72,
      shadow: false,
      hwaccel: false,
      className: 'spinner',
      zIndex: 2e9,
      top: 'auto',
      left: 'auto'
    };
    spinner = new Spinner(spinnerOpts).spin();
    $("#comix-spinner").append(spinner.el);
    window.gistId = gistId;
    src = "https://api.github.com/gists/" + gistId;
    if (gistId === "test") {
      src = "gist-test.html";
    }
    fail = function(event, xhr) {
      spinner.stop();
      $("#comix").css("display", "none");
      $("#error").css("display", "block");
      $("#error-response").text(xhr != null ? xhr.responseText : void 0);
      $("#error-gist-number").text("#" + gistId);
      $("#error-gist-link").attr("href", src).text(src);
      $("#error-gist-index-link").attr("href", "https://gist.github.com/" + gistId);
      _gaq.push(['_trackPageview', '/error/' + gistId]);
      return console.log("failed to fetch the gist content");
    };
    $(document).ajaxError(fail);
    console.log("fetching " + src + "...");
    return $.get(src, function(content) {
      var $banner, $comix, $placeholder, $stage, author, authorUrl, comix, d, date, description, doc, e, footer, header, ref, ref1, ref2, ref3, ref4, ref5, ref6;
      console.log("received", content);
      description = "A Comix";
      if (gistId === "test") {
        header = "some custom header";
        comix = content;
        footer = "some custom footer";
        description = "Hello world! TEST\nsecond line";
        author = "Antonin Hildebrand";
        authorUrl = "https://gist.github.com/4770953";
        date = "Jan 16, 2013";
      } else {
        if (typeof content === "string") {
          try {
            content = JSON.parse(content);
          } catch (error) {
            e = error;
            return fail();
          }
        }
        header = (ref = content.files) != null ? (ref1 = ref["header.html"]) != null ? ref1.content : void 0 : void 0;
        comix = (ref2 = content.files) != null ? (ref3 = ref2["index.html"]) != null ? ref3.content : void 0 : void 0;
        if (!comix) {
          fail(null, {
            responseText: "index.html file not found"
          });
          return;
        }
        footer = (ref4 = content.files) != null ? (ref5 = ref4["footer.html"]) != null ? ref5.content : void 0 : void 0;
        if (content.description) {
          description = content.description;
        }
        author = ((ref6 = content.user) != null ? ref6.login : void 0) || "anonymous";
        authorUrl = content.html_url;
        d = new Date(content.created_at);
        date = d.format("mmm d, yyyy");
      }
      description = description.split("\n")[0];
      $stage = $("<iframe/>", {
        "class": "stage",
        scrolling: "no",
        frameborder: 0,
        allowTransparency: "true"
      });
      $comix = $("#comix");
      $placeholder = $("#comix-placeholder");
      if (header) {
        $placeholder.append(header);
      }
      $placeholder.append($stage);
      if (footer) {
        $placeholder.append(footer);
      }
      $banner = $("#comix-banner");
      if (description) {
        $banner.find(".comix-title").append(description);
      }
      if (author != null) {
        $banner.find(".comix-author").append("by <a href=\"" + authorUrl + "\">" + author + "</a>");
      }
      if (date != null) {
        $banner.find(".comix-date").append("on " + date);
      }
      window.messageFromCMX = function(event, cmx) {
        var h, lH, lW, midW, rH, rW;
        switch (event) {
          case 'cmx:ready':
            window.cmxref = cmx;
            $comix.animate({
              opacity: 1
            });
            spinner.stop();
            lW = 0;
            lH = void 0;
            rW = 10000;
            $stage.css({
              width: rW + "px"
            });
            rH = $stage.contents().height();
            while (rW - lW > 2 && rW > 600) {
              midW = Math.floor((lW + rW) / 2);
              $stage.css({
                width: midW + "px"
              });
              h = $stage.contents().height();
              if (rH === h) {
                rW = midW;
              } else {
                lW = midW;
                lH = h;
              }
            }
            console.log("flex width detected w=" + rW + " h=" + rH);
            $stage.css({
              height: rH + "px",
              width: rW + "px"
            });
            $comix.css({
              width: rW + "px"
            });
            return $placeholder.css({
              width: rW + "px"
            });
        }
      };
      $comix.css({
        opacity: 0,
        display: "block"
      });
      doc = $stage.contents().get(0);
      doc.open();
      doc.write(comix);
      doc.close();
      return _gaq.push(['_trackPageview', '/gist/' + gistId]);
    });
  };

  $(function() {
    var hash;
    hash = location.hash.substring(1);
    if (hash) {
      return loadAndDisplayGist(hash);
    } else {
      return displayHomepage();
    }
  });

  $(window).hashchange(function() {
    return location.reload();
  });

}).call(this);
