// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/entity', 'cmx/gizmos/drawing_gizmo'], function(Entity, DrawingGizmo) {
    var Drawing;
    return Drawing = (function(superClass) {
      extend(Drawing, superClass);

      function Drawing(scene, drawlist) {
        if (drawlist == null) {
          drawlist = [];
        }
        this.drawlist = drawlist.map(function(call) {
          return call.map(function(x) {
            return _(x).clone();
          });
        });
        Drawing.__super__.constructor.call(this, scene);
        this.drawingBones = this.skelet.addBones([['HNDL', 0, 0, "h"]]);
      }

      Drawing.prototype.buildGizmo = function(root) {
        return this.gizmo = new DrawingGizmo(this, root);
      };

      Drawing.prototype.setPose = function(pose) {
        return this.skelet.setPose(pose, this.drawingBones);
      };

      Drawing.prototype.getPose = function() {
        return this.skelet.getPose(this.drawingBones);
      };

      Drawing.prototype.drawLayer = function(layer) {
        var i, item, itemsToBeRendered, len;
        Drawing.__super__.drawLayer.apply(this, arguments);
        itemsToBeRendered = _(this.drawlist).filter(function(item) {
          return layer === item[0];
        });
        if (!itemsToBeRendered.length) {
          return;
        }
        this.openFrame(((function(_this) {
          return function() {
            return _this.prepareFrame(_this.skelet.bone('HNDL'));
          };
        })(this)));
        for (i = 0, len = itemsToBeRendered.length; i < len; i++) {
          item = itemsToBeRendered[i];
          this.scene.renderer[item[1]].apply(this.scene.renderer, item.slice(2));
        }
        return this.closeFrame();
      };

      return Drawing;

    })(Entity);
  });

}).call(this);
