// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(['cmx/entity', 'cmx/gizmos/label_gizmo'], function(Entity, LabelGizmo) {
    var Label;
    return Label = (function(superClass) {
      extend(Label, superClass);

      function Label(scene, content) {
        Label.__super__.constructor.call(this, scene);
        this.labelBones = this.skelet.addBones([['HNDL', 0, 0, "h"], ['TEXT', -60, 0, "t"]]);
        this.skelet.addStructure({
          'HNDL': ['TEXT']
        });
        this.setContent(content);
      }

      Label.prototype.buildGizmo = function(root) {
        return this.gizmo = new LabelGizmo(this, root);
      };

      Label.prototype.setPose = function(pose) {
        return this.skelet.setPose(pose, this.labelBones);
      };

      Label.prototype.getPose = function() {
        return this.skelet.getPose(this.labelBones);
      };

      Label.prototype.setContent = function(content1) {
        this.content = content1;
      };

      Label.prototype.drawText = function() {
        var f;
        f = (function(_this) {
          return function(bone) {
            return " " + bone.x + "," + bone.y;
          };
        })(this);
        this.register(this.scene.renderer.openGroup({
          t: ((function(_this) {
            return function() {
              return "translate (" + (f(_this.skelet.bone('TEXT'))) + ")";
            };
          })(this))
        }));
        this.register(this.scene.renderer.text(this.content, {
          border: true
        }));
        return this.register(this.scene.renderer.closeGroup());
      };

      Label.prototype.drawLayer = function(layer) {
        Label.__super__.drawLayer.apply(this, arguments);
        if (layer === 0) {
          return this.drawText();
        }
      };

      return Label;

    })(Entity);
  });

}).call(this);
