// Generated by CoffeeScript 1.12.7
(function() {
  define(['cmx/gizmo'], function(Gizmo) {
    var Controller, instanceNumber;
    instanceNumber = 0;
    return Controller = (function() {
      function Controller(scenes) {
        this.scenes = scenes != null ? scenes : [];
        this.instanceNumber = ++instanceNumber;
        this.undoStack = [];
        this.redoStack = [];
      }

      Controller.prototype.makeEditable = function() {
        var i, len, ref, scene, sceneModel;
        ref = this.scenes;
        for (i = 0, len = ref.length; i < len; i++) {
          sceneModel = ref[i];
          scene = sceneModel.view;
          scene.buildGizmos();
          $(scene.rootElement).addClass("cmx-editable");
        }
        return $("html").bind("click", (function(_this) {
          return function(event) {
            if (d3.select(event.target).parents("cmx-selected").length > 0) {
              return;
            }
            return _this.unselectAll();
          };
        })(this));
      };

      Controller.prototype.unselectAll = function() {
        if (!this.previousSelection) {
          return;
        }
        this.previousSelection.unselect();
        this.previousSelection = void 0;
        $(".cmx-has-selected-gizmo").removeClass("cmx-has-selected-gizmo");
        return $("html").removeClass("cmx-active-selection");
      };

      Controller.prototype.registerUndo = function(fn) {
        return this.undoStack.push(fn);
      };

      Controller.prototype.undo = function() {
        var action;
        if (!this.undoStack.length) {
          return;
        }
        action = this.undoStack.pop();
        return action();
      };

      Controller.prototype.registerRedo = function(fn) {
        return this.redoStack.push(fn);
      };

      Controller.prototype.redo = function() {
        var action;
        if (!this.redoStack.length) {
          return;
        }
        action = this.redoStack.pop();
        return action();
      };

      return Controller;

    })();
  });

}).call(this);
