// Generated by CoffeeScript 1.12.7
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    slice = [].slice;

  define(['cmx/drawable'], function(Drawable) {
    var Gizmo, initialUndoValue, undoEval;
    initialUndoValue = void 0;
    undoEval = void 0;
    return Gizmo = (function(superClass) {
      extend(Gizmo, superClass);

      Gizmo.prototype.CONTROL_POINT_RADIUS = 3;

      function Gizmo(entity, root) {
        this.entity = entity;
        Gizmo.__super__.constructor.call(this, this.entity.scene);
        this.entity.gizmo = this;
        this.leafGizmo = this.build(root);
      }

      Gizmo.prototype.build = function(root) {
        return this.ΔrootGizmo = root.append("g").attr("class", "cmx-gizmo root");
      };

      Gizmo.prototype.controlDragStart = function(bone) {
        $(this.scene.rootElement).addClass("cmx-something-is-being-dragged");
        this.entity.highlightBones(this.ΔskeletonGizmo, this.entity.skelet.affectedBones(bone.name));
        return $("html").addClass("cmx-force-move-cursor");
      };

      Gizmo.prototype.controlDragEnd = function(bone) {
        $(this.scene.rootElement).removeClass("cmx-something-is-being-dragged");
        this.entity.unhighlightBones(this.ΔskeletonGizmo);
        return $("html").removeClass("cmx-force-move-cursor");
      };

      Gizmo.prototype.controlUndoOpen = function() {
        var getter, params, setter, what;
        what = arguments[0], params = 2 <= arguments.length ? slice.call(arguments, 1) : [];
        getter = "get" + _.str.classify(what);
        setter = "set" + _.str.classify(what);
        undoEval = (function(_this) {
          return function(val) {
            if (val) {
              return _this.entity[setter].call(_this.entity, val);
            } else {
              return _this.entity[getter].apply(_this.entity, params);
            }
          };
        })(this);
        return initialUndoValue = undoEval();
      };

      Gizmo.prototype.controlUndoClose = function() {
        var finalUndoValue;
        finalUndoValue = undoEval();
        return ((function(_this) {
          return function(original, modified, evaluator) {
            var action;
            action = function() {
              evaluator(original);
              _this.entity.throttledUpdate();
              return _this.scene.cmx.registerRedo(function() {
                evaluator(modified);
                _this.entity.throttledUpdate();
                return _this.scene.cmx.registerUndo(action);
              });
            };
            return _this.scene.cmx.registerUndo(action);
          };
        })(this))(initialUndoValue, finalUndoValue, undoEval);
      };

      Gizmo.prototype.unselect = function() {
        this.ΔentityGizmo.classed("cmx-selected", false);
        return this.ΔentityGizmo.select(".cmx-force-unselected").classed("cmx-force-unselected", false);
      };

      Gizmo.prototype.select = function() {
        this.scene.cmx.unselectAll();
        this.ΔentityGizmo.classed("cmx-selected", true);
        this.ΔentityGizmo.select(".root").classed("cmx-force-unselected", true);
        $(this.scene.rootElement).addClass("cmx-has-selected-gizmo");
        $("html").addClass("cmx-active-selection");
        return this.scene.cmx.previousSelection = this;
      };

      return Gizmo;

    })(Drawable);
  });

}).call(this);
