// Generated by CoffeeScript 1.12.7
(function() {
  var slice = [].slice;

  define(["cmx/models/scene_model", "cmx/models/actor_model", "cmx/models/bubble_model", "cmx/models/drawing_model", "cmx/models/label_model"], function() {
    var Parser, defaultModels, i, klass, len, modelClasses;
    modelClasses = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    defaultModels = {};
    for (i = 0, len = modelClasses.length; i < len; i++) {
      klass = modelClasses[i];
      defaultModels[klass.name] = klass;
    }
    return Parser = (function() {
      function Parser(cmx, models) {
        this.cmx = cmx;
        this.models = models != null ? models : defaultModels;
      }

      Parser.prototype.createFrame = function() {
        this.$frame = $("<iframe>", {
          "class": "cmx-parser",
          frameborder: 0,
          style: "display:none"
        });
        this.$frame.appendTo("body");
        return this.doc = this.$frame.contents().get(0);
      };

      Parser.prototype.writeContent = function(markup) {
        this.doc.open();
        this.doc.write(markup);
        return this.doc.close();
      };

      Parser.prototype.parseMarkup = function(markup) {
        this.createFrame();
        this.writeContent(markup);
        return this.parseDoc(this.doc);
      };

      Parser.prototype.lookupModelClass = function(modelName) {
        return this.models[modelName + "Model"];
      };

      Parser.prototype.collectProps = function($el) {
        var attr, content, e, j, key, len1, params, ref, res, val;
        res = {};
        content = $el.html();
        if (content) {
          res["content"] = content;
        }
        content = _.str.trim($el.css('content'), " \t\n'");
        if (content && content !== "none") {
          if (content[0] !== "{") {
            content = "{" + content + "}";
          }
          try {
            params = $.parseJSON(content);
            $.extend(res, params);
          } catch (error) {
            e = error;
            console.error(e);
          }
        }
        ref = $el.get(0).attributes;
        for (j = 0, len1 = ref.length; j < len1; j++) {
          attr = ref[j];
          key = attr.name.toLowerCase();
          val = attr.value;
          res[key] = val;
        }
        return res;
      };

      Parser.prototype.parseElement = function($el) {
        var model, modelClass, props, tag;
        model = $el.data('cmx-model');
        if (!model) {
          tag = _.str.classify($el.prop('tagName').toLowerCase());
          modelClass = this.lookupModelClass(tag);
          if (!modelClass) {
            return;
          }
          model = new modelClass(this.cmx);
          model.source = $el.get(0);
          $el.data('cmx-model', model);
        }
        props = this.collectProps($el);
        model.set(props);
        return model;
      };

      Parser.prototype.parseDoc = function(doc) {
        var $doc, $scene, j, len1, ref, res, scene, sceneModel, walk;
        $doc = $(doc);
        walk = (function(_this) {
          return function($el) {
            var $child, child, childModel, j, len1, model, ref;
            model = _this.parseElement($el);
            ref = $el.children();
            for (j = 0, len1 = ref.length; j < len1; j++) {
              child = ref[j];
              $child = $(child);
              childModel = walk($child);
              if (!childModel) {
                continue;
              }
              childModel.parent = model;
              model.children.push(childModel);
            }
            return model;
          };
        })(this);
        res = [];
        ref = $doc.find("scene");
        for (j = 0, len1 = ref.length; j < len1; j++) {
          scene = ref[j];
          $scene = $(scene);
          sceneModel = walk($scene);
          sceneModel.source = scene;
          res.push(sceneModel);
        }
        this.cmx.scenes = res;
        return res;
      };

      return Parser;

    })();
  });

}).call(this);
