// Generated by CoffeeScript 1.12.7
(function() {
  define(['cmx/bone'], function(Bone) {
    var Skelet;
    return Skelet = (function() {
      function Skelet(bonedefs) {
        if (bonedefs == null) {
          bonedefs = [];
        }
        this.bones = [];
        this.addBones(bonedefs);
        this.structure = {};
      }

      Skelet.prototype.addBones = function(bonedefs) {
        var args, j, len, list;
        if (bonedefs == null) {
          bonedefs = [];
        }
        list = [];
        for (j = 0, len = bonedefs.length; j < len; j++) {
          args = bonedefs[j];
          this.bones.push((function(func, args, ctor) {
            ctor.prototype = func.prototype;
            var child = new ctor, result = func.apply(child, args);
            return Object(result) === result ? result : child;
          })(Bone, args, function(){}));
          list.push(this.bones.length - 1);
        }
        return list;
      };

      Skelet.prototype.addStructure = function(defs) {
        var arg, results, val;
        if (defs == null) {
          defs = {};
        }
        results = [];
        for (arg in defs) {
          val = defs[arg];
          results.push(this.structure[arg] = val);
        }
        return results;
      };

      Skelet.prototype.boneIndex = function(name) {
        var bone, i, j, len, ref;
        ref = this.bones;
        for (i = j = 0, len = ref.length; j < len; i = ++j) {
          bone = ref[i];
          if (name === bone.name) {
            return i;
          }
        }
        return null;
      };

      Skelet.prototype.bone = function(name) {
        var index;
        index = this.boneIndex(name);
        return this.bones[index];
      };

      Skelet.prototype.bonesWithIndices = function(boneIndices) {
        return boneIndices.map((function(_this) {
          return function(index) {
            return _this.bones[index];
          };
        })(this));
      };

      Skelet.prototype.moveBone = function(boneNames, dx, dy, absolute) {
        var affectedBones, bone, boneName, j, len, mx, my, results;
        if (absolute == null) {
          absolute = false;
        }
        if (!_.isArray(boneNames)) {
          boneNames = [boneNames];
        }
        results = [];
        for (j = 0, len = boneNames.length; j < len; j++) {
          boneName = boneNames[j];
          bone = this.boneIndex(boneName);
          dx = Math.round(dx);
          dy = Math.round(dy);
          mx = this.bones[bone].x;
          my = this.bones[bone].y;
          if (absolute) {
            this.bones[bone].x = dx;
            this.bones[bone].y = dy;
          } else {
            this.bones[bone].x += dx;
            this.bones[bone].y += dy;
          }
          mx -= this.bones[bone].x;
          my -= this.bones[bone].y;
          affectedBones = this.affectedBones(boneName, false);
          results.push((function() {
            var k, len1, results1;
            results1 = [];
            for (k = 0, len1 = affectedBones.length; k < len1; k++) {
              boneName = affectedBones[k];
              bone = this.boneIndex(boneName);
              this.bones[bone].x -= mx;
              results1.push(this.bones[bone].y -= my);
            }
            return results1;
          }).call(this));
        }
        return results;
      };

      Skelet.prototype.affectedBones = function(boneNames, addSelf) {
        var a, boneName, j, len, res;
        if (addSelf == null) {
          addSelf = true;
        }
        if (!_.isArray(boneNames)) {
          boneNames = [boneNames];
        }
        res = [];
        for (j = 0, len = boneNames.length; j < len; j++) {
          boneName = boneNames[j];
          a = this.structure[boneName];
          if (a) {
            res = res.concat(a);
          }
        }
        if (addSelf) {
          res.concat(boneNames);
        }
        return _.uniq(res);
      };

      Skelet.prototype.getPose = function(boneIndices) {
        var bone, boneIndex, j, len, pose;
        pose = [];
        for (j = 0, len = boneIndices.length; j < len; j++) {
          boneIndex = boneIndices[j];
          bone = this.bones[boneIndex];
          if (!bone) {
            continue;
          }
          pose.push([bone.x, bone.y]);
        }
        return pose;
      };

      Skelet.prototype.setPose = function(pose, boneIndices) {
        var i, index, j, len, point, results;
        results = [];
        for (i = j = 0, len = pose.length; j < len; i = ++j) {
          point = pose[i];
          index = boneIndices[i];
          if (index === void 0) {
            continue;
          }
          if (index >= this.bones.length) {
            continue;
          }
          this.bones[index].x = point[0];
          results.push(this.bones[index].y = point[1]);
        }
        return results;
      };

      return Skelet;

    })();
  });

}).call(this);
