// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    var fn;
    fn = function() {
      return $(".bs-docs-social-buttons").css("opacity", 0).css("display", "block").animate({
        opacity: 1
      });
    };
    return setTimeout(fn, 2000);
  });

}).call(this);
